// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADu-9MpGar4taFN06RmTn8kWStZ0dZd2Y',
    appId: '1:455611943887:web:8d6adba4d8a3d05b9c20ba',
    messagingSenderId: '455611943887',
    projectId: 'plant-monitor-test',
    authDomain: 'plant-monitor-test.firebaseapp.com',
    storageBucket: 'plant-monitor-test.appspot.com',
    measurementId: 'G-RWH10KLS2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT22XrcKPHclICFpKy_dS4dPhYfpb-NQY',
    appId: '1:455611943887:android:5d4998d0253575cf9c20ba',
    messagingSenderId: '455611943887',
    projectId: 'plant-monitor-test',
    storageBucket: 'plant-monitor-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsJhpLJlCb5ja5fOi_uP2DzSrbtZGgDfo',
    appId: '1:455611943887:ios:bd43a7e3b6ee5a8b9c20ba',
    messagingSenderId: '455611943887',
    projectId: 'plant-monitor-test',
    storageBucket: 'plant-monitor-test.appspot.com',
    iosBundleId: 'com.example.plantClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsJhpLJlCb5ja5fOi_uP2DzSrbtZGgDfo',
    appId: '1:455611943887:ios:0e253d230de1d6589c20ba',
    messagingSenderId: '455611943887',
    projectId: 'plant-monitor-test',
    storageBucket: 'plant-monitor-test.appspot.com',
    iosBundleId: 'com.example.plantClient.RunnerTests',
  );
}
